### ISSUE TITLE
Create patch generation API usable by the CLI

### ISSUE THREAD

**Issue by bkuschel** [qlik-oss/qliksense-operator#12]
When the [CLI](https://github.com/qlik-oss/sense-installer) operates in "local" mode, it takes the role of generating the manifest and generating patches. The operator needs to be imported as module into the [CLI](https://github.com/qlik-oss/sense-installer) to provide the capability it already has for the kubernetes operator.

**Comment by ffoysal** [comment]
https://github.com/qlik-oss/k-apis/pull/4
